apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: flo-permissive
spec:
  privileged: false
  hostNetwork: true
  allowPrivilegeEscalation: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
